import { afterEach, describe, expect, it } from "vitest";
import { existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, readlinkSync, rmSync, writeFileSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";
import type { AgentConfig } from "../types";
import {
  buildCodexHomeOverlay,
  parseBashPattern,
  translatePermissionRules,
} from "./codexPermissions";

function makeAgent(overrides: Partial<AgentConfig> = {}): AgentConfig {
  return {
    filePath: "_fleet/agents/test.md",
    name: "test-agent",
    model: "",
    adapter: "codex",
    permissionMode: "workspace-write",
    maxRetries: 0,
    skills: [],
    mcpServers: [],
    enabled: true,
    timeout: 300,
    approvalRequired: [],
    memory: false,
    memoryMaxEntries: 50,
    memoryTokenBudget: 1500,
    reflection: { enabled: false, schedule: "0 3 * * *", recurrenceThreshold: 3, proposeSkills: false },
    tags: [],
    avatar: "",
    body: "",
    contextBody: "",
    skillsBody: "",
    env: {},
    permissionRules: { allow: [], deny: [] },
    isFolder: false,
    heartbeatEnabled: false,
    heartbeatSchedule: "",
    heartbeatBody: "",
    heartbeatNotify: false,
    heartbeatChannel: "",
    ...overrides,
  };
}

describe("parseBashPattern", () => {
  it("strips a trailing wildcard into a prefix", () => {
    expect(parseBashPattern("git push *")).toEqual({ tokens: ["git", "push"] });
    expect(parseBashPattern("curl *")).toEqual({ tokens: ["curl"] });
  });

  it("keeps an exact command with no wildcard", () => {
    expect(parseBashPattern("git status")).toEqual({ tokens: ["git", "status"] });
  });

  it("handles a mid-flag prefix with trailing wildcard", () => {
    expect(parseBashPattern("git commit -m *")).toEqual({ tokens: ["git", "commit", "-m"] });
  });

  it("rejects mid-pattern wildcards", () => {
    expect(parseBashPattern("git * --force")).toHaveProperty("error");
  });

  it("rejects embedded wildcards", () => {
    expect(parseBashPattern("./deploy*")).toHaveProperty("error");
    expect(parseBashPattern("*.sh")).toHaveProperty("error");
  });

  it("rejects an empty or bare-wildcard pattern", () => {
    expect(parseBashPattern("")).toHaveProperty("error");
    expect(parseBashPattern("*")).toHaveProperty("error");
  });
});

describe("translatePermissionRules", () => {
  it("translates deny → forbidden and allow → allow prefix rules", () => {
    const agent = makeAgent({
      permissionRules: {
        deny: ["Bash(git push *)", "Bash(rm -rf *)"],
        allow: ["Bash(ls *)", "Bash(git status)"],
      },
    });
    const { rulesText, dropped, emitted } = translatePermissionRules(agent);
    expect(dropped).toEqual([]);
    expect(emitted).toBe(4);
    expect(rulesText).toContain('prefix_rule(pattern=["git", "push"], decision="forbidden"');
    expect(rulesText).toContain('prefix_rule(pattern=["rm", "-rf"], decision="forbidden"');
    expect(rulesText).toContain('prefix_rule(pattern=["ls"], decision="allow"');
    expect(rulesText).toContain('prefix_rule(pattern=["git", "status"], decision="allow"');
    expect(rulesText).toMatch(/^# Generated by Agent Fleet/);
  });

  it("drops tool-name rules with a sandbox-governed reason", () => {
    const agent = makeAgent({ permissionRules: { allow: ["Read", "Write", "Edit"], deny: [] } });
    const { rulesText, dropped } = translatePermissionRules(agent);
    expect(rulesText).toBeNull();
    expect(dropped.map((d) => d.rule)).toEqual(["Read", "Write", "Edit"]);
    expect(dropped[0]!.reason).toMatch(/sandbox/);
  });

  it("drops mid-pattern wildcards but keeps the translatable siblings", () => {
    const agent = makeAgent({
      permissionRules: { deny: ["Bash(git * --force)", "Bash(sudo *)"], allow: [] },
    });
    const { rulesText, dropped, emitted } = translatePermissionRules(agent);
    expect(emitted).toBe(1);
    expect(rulesText).toContain('prefix_rule(pattern=["sudo"], decision="forbidden"');
    expect(dropped.map((d) => d.rule)).toEqual(["Bash(git * --force)"]);
  });

  it("ignores mcp__ entries (scoped via config overrides, not rules)", () => {
    const agent = makeAgent({ permissionRules: { allow: ["mcp__notion", "Bash(ls *)"], deny: [] } });
    const { rulesText, dropped, emitted } = translatePermissionRules(agent);
    expect(emitted).toBe(1);
    expect(dropped).toEqual([]);
    expect(rulesText).toContain('pattern=["ls"]');
    expect(rulesText).not.toContain("mcp__");
  });

  it("returns null rulesText when nothing is translatable", () => {
    const agent = makeAgent({ permissionRules: { allow: [], deny: [] } });
    expect(translatePermissionRules(agent).rulesText).toBeNull();
  });

  it("escapes tokens that contain quotes", () => {
    const agent = makeAgent({ permissionRules: { deny: ['Bash(echo "hi" *)'], allow: [] } });
    const { rulesText } = translatePermissionRules(agent);
    // JSON-escaped quotes produce a valid Starlark string literal.
    expect(rulesText).toContain('"\\"hi\\""');
  });
});

describe("buildCodexHomeOverlay", () => {
  const created: string[] = [];

  afterEach(() => {
    for (const dir of created.splice(0)) {
      try { rmSync(dir, { recursive: true, force: true }); } catch { /* ignore */ }
    }
  });

  function makeFakeCodexHome(): string {
    const home = mkdtempSync(join(tmpdir(), "af-fake-codex-"));
    created.push(home);
    writeFileSync(join(home, "auth.json"), '{"token":"x"}', "utf-8");
    writeFileSync(join(home, "config.toml"), "model = \"gpt-5.5\"\n", "utf-8");
    mkdirSync(join(home, "sessions"), { recursive: true });
    mkdirSync(join(home, "rules"), { recursive: true });
    writeFileSync(join(home, "rules", "global.rules"), 'prefix_rule(pattern=["shutdown"], decision="forbidden")\n', "utf-8");
    return home;
  }

  it("symlinks every real entry except rules/, and writes our rules", () => {
    const home = makeFakeCodexHome();
    const agent = makeAgent({ name: "overlay-test" });
    const result = buildCodexHomeOverlay(agent, "# rules\nprefix_rule(pattern=[\"ls\"], decision=\"allow\")\n", home);
    expect(result).not.toBeNull();
    created.push(result!.codexHome);

    // auth.json + config.toml + sessions are symlinks pointing back at real home.
    for (const entry of ["auth.json", "config.toml", "sessions"]) {
      const linkPath = join(result!.codexHome, entry);
      expect(lstatSync(linkPath).isSymbolicLink()).toBe(true);
      expect(readlinkSync(linkPath)).toBe(join(home, entry));
    }

    // rules/ is a REAL dir we own, not a symlink to the user's rules.
    const rulesDir = join(result!.codexHome, "rules");
    expect(lstatSync(rulesDir).isSymbolicLink()).toBe(false);
    expect(existsSync(result!.rulesPath)).toBe(true);
    expect(readFileSync(result!.rulesPath, "utf-8")).toContain('pattern=["ls"]');
  });

  it("unions the user's global rules in alongside ours", () => {
    const home = makeFakeCodexHome();
    const agent = makeAgent({ name: "union-test" });
    const result = buildCodexHomeOverlay(agent, "prefix_rule(pattern=[\"ls\"], decision=\"allow\")\n", home);
    created.push(result!.codexHome);
    const rulesDir = join(result!.codexHome, "rules");
    const files = readdirSync(rulesDir);
    expect(files).toContain("agent-fleet.rules");
    expect(files).toContain("user-global.rules"); // user's global rule preserved
    expect(readFileSync(join(rulesDir, "user-global.rules"), "utf-8")).toContain("shutdown");
  });

  it("returns null when the real codex home doesn't exist", () => {
    const agent = makeAgent({ name: "no-home" });
    expect(buildCodexHomeOverlay(agent, "x", join(tmpdir(), "definitely-not-here-af"))).toBeNull();
  });

  it("refreshes the rules on a second call (overwrites our file)", () => {
    const home = makeFakeCodexHome();
    const agent = makeAgent({ name: "refresh-test" });
    const first = buildCodexHomeOverlay(agent, "prefix_rule(pattern=[\"ls\"], decision=\"allow\")\n", home);
    created.push(first!.codexHome);
    const second = buildCodexHomeOverlay(agent, "prefix_rule(pattern=[\"cat\"], decision=\"allow\")\n", home);
    expect(second!.codexHome).toBe(first!.codexHome); // stable per-agent path
    expect(readFileSync(second!.rulesPath, "utf-8")).toContain('pattern=["cat"]');
    expect(readFileSync(second!.rulesPath, "utf-8")).not.toContain('pattern=["ls"]');
  });

  it("gives distinct overlays to agents whose names slug identically", () => {
    const home = makeFakeCodexHome();
    // Names differ only by punctuation → identical slug, but distinct filePaths.
    const a = makeAgent({ name: "deploy bot", filePath: "_fleet/agents/deploy-bot-a.md" });
    const b = makeAgent({ name: "deploy.bot", filePath: "_fleet/agents/deploy-bot-b.md" });
    const ra = buildCodexHomeOverlay(a, "prefix_rule(pattern=[\"ls\"], decision=\"allow\")\n", home);
    const rb = buildCodexHomeOverlay(b, "prefix_rule(pattern=[\"cat\"], decision=\"allow\")\n", home);
    created.push(ra!.codexHome, rb!.codexHome);
    expect(ra!.codexHome).not.toBe(rb!.codexHome); // no cross-contamination
    expect(readFileSync(ra!.rulesPath, "utf-8")).toContain('pattern=["ls"]');
    expect(readFileSync(rb!.rulesPath, "utf-8")).toContain('pattern=["cat"]');
  });
});
