import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";
import type { AgentConfig } from "../types";
import { parseBashPattern } from "./codexPermissions";

/**
 * Pi extension code generation.
 *
 * Pi ships no permission system and no structured-output flag — both are
 * explicitly extension territory ("No permission popups… build your own
 * confirmation flow with extensions"). This module generates small TypeScript
 * extension files per run and returns paths to load via `pi --extension`,
 * which works even under `--no-extensions` (explicit `-e` paths always load).
 *
 * Generated code is plain transpile-friendly TS: no imports beyond what the
 * extension host resolves itself, with minimal local interfaces standing in
 * for the host's ambient types so the shapes the gate relies on stay explicit.
 * The files live in a per-run temp dir removed by the invocation's cleanup
 * handle (same contract as the Codex output-schema temp file).
 */

/** Tool name the generated structured-output extension registers. Also the
 *  name `parsePiExecOutput` looks for when extracting the validated result. */
export const PI_STRUCTURED_OUTPUT_TOOL = "structured_output";

export interface PiGeneratedExtensions {
  /** Absolute paths to pass via repeated `--extension` flags. */
  paths: string[];
  /** Remove the temp dir. Safe to call more than once. */
  cleanup: () => void;
  /** Rules that could not be enforced by the gate, with reasons (surfaced as
   *  a one-time console warning by the adapter). */
  droppedRules: Array<{ rule: string; reason: string }>;
}

/**
 * Translate `permissionRules.deny` into token-prefix matchers for the
 * generated bash gate. Reuses the Codex `Bash(...)` pattern parser so the two
 * backends drop exactly the same untranslatable shapes (tool-name rules,
 * mid-pattern wildcards), keeping the documented cross-adapter semantics.
 * Allow rules are not translated at all: the gate is deny-only (there is no
 * closed allowlist on Pi — the same documented limitation as Codex).
 */
export function translatePiGateRules(agent: AgentConfig): {
  deny: string[][];
  dropped: Array<{ rule: string; reason: string }>;
} {
  const deny: string[][] = [];
  const dropped: Array<{ rule: string; reason: string }> = [];

  for (const raw of agent.permissionRules.deny) {
    const entry = raw.trim();
    if (!entry) continue;
    if (entry.startsWith("mcp__")) continue; // MCP scoping is projection's job
    const bash = entry.match(/^Bash\((.*)\)$/s);
    if (!bash) {
      dropped.push({
        rule: entry,
        reason: /^[A-Z][A-Za-z]*$/.test(entry)
          ? "tool-name rules are governed by the Permission Mode tool set, not the gate"
          : "not a Bash(...) command pattern",
      });
      continue;
    }
    const parsed = parseBashPattern(bash[1]!);
    if ("error" in parsed) {
      dropped.push({ rule: entry, reason: parsed.error });
      continue;
    }
    deny.push(parsed.tokens);
  }

  return { deny, dropped };
}

/**
 * Source for the bash permission-gate extension. Deny rules are hard blocks;
 * there is no closed allowlist (the same documented limitation as the Codex
 * execpolicy translation). Blocks are returned to the model as tool errors,
 * so the agent can adapt rather than silently losing the call.
 *
 * IMPORTANT — enforcement strength: this gate matches the COMMAND STRING the
 * model passed to bash, not the argv of processes the shell actually spawns
 * (Codex execpolicy hooks the latter). To narrow the gap, tokens are
 * quote-stripped and deny sequences match at ANY position in the token
 * stream, which catches `sudo rm -rf`, `true && rm -rf`, `env rm -rf`, and
 * `rm "-rf"` — at the cost of occasionally over-blocking (e.g. `echo "rm
 * -rf"` also trips a `rm -rf` deny). Over-blocking is the safe direction for
 * a deny gate. Determined shell-quoting tricks can still slip through: treat
 * deny rules on Pi as guardrails, not a security boundary.
 */
export function renderPiGateExtension(deny: string[][], agentName: string): string {
  return `// Generated by Agent Fleet for agent ${JSON.stringify(agentName)}. Do not edit — regenerated each run.
// Blocks bash commands whose token stream contains a denied sequence.
const DENY: string[][] = ${JSON.stringify(deny)};

function normTokens(command: string): string[] {
  return command
    .trim()
    .split(/\\s+/)
    .map((t: string) => t.replace(/^['"]+|['"]+$/g, ""))
    .filter(Boolean);
}

function containsSequence(tokens: string[], seq: string[]): boolean {
  if (seq.length === 0) return false;
  for (let i = 0; i + seq.length <= tokens.length; i++) {
    let ok = true;
    for (let j = 0; j < seq.length; j++) {
      if (tokens[i + j] !== seq[j]) { ok = false; break; }
    }
    if (ok) return true;
  }
  return false;
}

// The shapes this gate relies on from the extension host. If Pi's tool_call
// event schema drifts (e.g. input.command moves), these break the transpile
// loudly instead of the gate silently matching nothing.
interface ToolCallEvent {
  toolName: string;
  input?: { command?: unknown };
}
interface BlockResult {
  block: true;
  reason: string;
}
interface PiHost {
  on(
    hook: "tool_call",
    handler: (event: ToolCallEvent, ctx: unknown) => Promise<BlockResult | undefined>,
  ): void;
}

export default function (pi: PiHost) {
  pi.on("tool_call", async (event: ToolCallEvent, _ctx: unknown) => {
    if (event.toolName !== "bash") return undefined;
    const command = typeof event.input?.command === "string" ? event.input.command : "";
    const tokens = normTokens(command);
    for (const seq of DENY) {
      if (containsSequence(tokens, seq)) {
        return {
          block: true,
          reason:
            "Blocked by this agent's permission rules (deny: " + seq.join(" ") + "). " +
            "Do not retry variations of this command.",
        };
      }
    }
    return undefined;
  });
}
`;
}

/**
 * Source for the structured-output extension: registers a terminating tool
 * whose parameters are the task's JSON schema, so the model ends its run on a
 * schema-shaped tool call. The adapter extracts the call's arguments from the
 * JSON event stream; ExecutionManager's existing fail-closed check rejects the
 * run if the tool was never called.
 */
export function renderPiStructuredOutputExtension(schemaJson: string): string {
  return `// Generated by Agent Fleet. Do not edit — regenerated each run.
// Terminating structured-output tool; parameters are the task's JSON schema.
const SCHEMA: Record<string, unknown> = ${schemaJson};

// The registerTool surface this extension relies on from the host.
interface ToolResult {
  content: Array<{ type: "text"; text: string }>;
  details: unknown;
  terminate: boolean;
}
interface PiHost {
  registerTool(tool: {
    name: string;
    label: string;
    description: string;
    promptSnippet: string;
    promptGuidelines: string[];
    parameters: Record<string, unknown>;
    execute(toolCallId: string, params: unknown): Promise<ToolResult>;
  }): void;
}

export default function (pi: PiHost) {
  pi.registerTool({
    name: ${JSON.stringify(PI_STRUCTURED_OUTPUT_TOOL)},
    label: "Structured Output",
    description:
      "Return the final structured result. Call this exactly once, as your last action, " +
      "with arguments matching the required schema.",
    promptSnippet: "Emit the final answer as a terminating structured_output tool call",
    promptGuidelines: [
      "This task requires structured output: finish by calling structured_output with the result.",
      "After calling structured_output, do not emit another assistant response in the same turn.",
    ],
    parameters: SCHEMA,
    async execute(_toolCallId: string, params: unknown) {
      return {
        content: [{ type: "text", text: "Structured output recorded." }],
        details: params,
        terminate: true,
      };
    },
  });
}
`;
}

/**
 * Materialize the generated extensions for one run. Returns null when the run
 * needs neither (no schema, no deny rules). Throws only for the structured-
 * output write — losing the schema must fail the run (fail-closed), while a
 * failed gate write degrades to a loud warning by the caller.
 */
export function writePiExtensions(opts: {
  agent: AgentConfig;
  outputSchema?: string;
}): PiGeneratedExtensions | null {
  const { deny, dropped } = translatePiGateRules(opts.agent);
  const wantGate = deny.length > 0;
  const wantSchema = Boolean(opts.outputSchema);
  if (!wantGate && !wantSchema) {
    return dropped.length > 0
      ? { paths: [], cleanup: () => undefined, droppedRules: dropped }
      : null;
  }

  let dir: string | undefined;
  try {
    // Same dedicated root + pid-marker convention as the MCP overlays
    // (mcpProjection.ts: piOverlayRoot / PI_OVERLAY_PID_FILE) so the stale-dir
    // sweep's liveness guard covers these too — a chat session's gate dir
    // lives as long as the process, with its mtime frozen at spawn. Mirrored
    // rather than imported: adapters must not depend on services (the
    // projection module already imports the adapter registry).
    mkdirSync(join(tmpdir(), "agent-fleet-pi"), { recursive: true });
    dir = mkdtempSync(join(tmpdir(), "agent-fleet-pi", "ext-"));
    writeFileSync(join(dir, ".af-pid"), String(process.pid), "utf-8");
    const extDir = dir;
    const paths: string[] = [];

    if (wantGate) {
      const gatePath = join(extDir, "af-gate.ts");
      writeFileSync(gatePath, renderPiGateExtension(deny, opts.agent.name), "utf-8");
      paths.push(gatePath);
    }
    if (wantSchema && opts.outputSchema) {
      const schemaPath = join(extDir, "af-structured-output.ts");
      writeFileSync(schemaPath, renderPiStructuredOutputExtension(opts.outputSchema), "utf-8");
      paths.push(schemaPath);
    }

    return {
      paths,
      droppedRules: dropped,
      cleanup: () => {
        try {
          rmSync(extDir, { recursive: true, force: true });
        } catch {
          /* best-effort — temp dir, the OS reclaims it */
        }
      },
    };
  } catch (err) {
    if (dir) {
      try {
        rmSync(dir, { recursive: true, force: true });
      } catch {
        /* best-effort cleanup after a failed write */
      }
    }
    if (wantSchema) {
      // Fail closed: a schema-bearing run without its extension would return
      // prose while looking machine-readable.
      throw new Error(
        "Couldn't write the Pi structured-output extension: " +
          (err instanceof Error ? err.message : String(err)),
      );
    }
    // Gate-only failure: degrade loudly rather than kill the run — parity with
    // the Codex overlay's soft failure paths.
    console.warn(
      `Agent Fleet: couldn't write the Pi permission gate for agent "${opts.agent.name}"; ` +
        "this run's deny rules are NOT enforced.",
      err,
    );
    return dropped.length > 0
      ? { paths: [], cleanup: () => undefined, droppedRules: dropped }
      : null;
  }
}
